gmf:
    alias: gmf_imf
    num_epochs: 10
    batch_size: 1024
    optimizer: adam
    adam_lr: 1e-3
    latent_dim: 8
    num_negatives: 10
    l2_regularization: 0.0 # 0.1
    use_cuda: True
    model_dir: "checkpoints/{}_Epoch{}_HR{:.4f}.model"

mlp:
    alias: mlp_imf
    num_epochs: 10
    batch_size: 512
    optimizer: adam
    adam_lr: 1e-3
    latent_dim: 8
    num_negatives: 10
    layers: [16, 64, 32, 16, 8]
    l2_regularization: 0.0000001 # 0.1
    use_cuda: True
    pretrain: False
    pretrain_mf: None
    dropout: 0.3
    model_dir: "checkpoints/{}_Epoch{}_HR{:.4f}.model"

neumf:
    alias: neural_imf
    num_epochs: 10
    batch_size: 512
    optimizer: adam
    adam_lr: 1e-3
    latent_dim_mf: 8
    latent_dim_mlp: 8
    num_negatives: 10
    layers: [16, 64, 32, 16, 8]
    l2_regularization: 0.000001 # 0.1
    use_cuda: True
    pretrain: False
    pretrain_mf: None
    dropout: 0.3
    model_dir: "checkpoints/{}_Epoch{}_HR{:.4f}.model"
